<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>IrregularSolidsCalculator</RootNamespace>
    <AssemblyName>IrregularSolidsCalculator</AssemblyName>
    <TargetFramework>net6.0</TargetFramework>
    <OptionStrict>On</OptionStrict>
    <OptionExplicit>On</OptionExplicit>
  </PropertyGroup>

</Project>
